@startuml
sprite $alarm [48x48/16z] {
xT376OGm38L1TJ3zTxkdpSZYVVZ8JuOXkVQ4mBxAD9pINmSJNv-OhaB0bpSW6Lg4vwk22-btvhwwTdXBx_Q3lttrNVS6xw9lU7VPwCsFxm6pb_1lurmPps-e
FVdQ2mO2kP_ZUsVslhPZyG3cuztg1m
}
@enduml
