@startuml
sprite $addin [70x72/16z] {
xTO5aiCm30NGFnhNgKd__gTT9Yj5LLb-6Go8GiR6TbtP5jma3pxH3B_CDqj443B3IVbHH2da7YwTanxH42dme97W8Doa5lc1jQIIFsmqodGqPnnKb5SPWfN4
wmaiEYYCGO-4YIWzp8GpNHecXIxb-zPIlgwM_xdypqLTjLYfybfAjWHZHuy5Heu9q-WX8Jrr64e7ZMaf8U8Pp9j4QI5HUiYjfiV0R4-FFMOQK8f4F7FIFJ4w
dhokrgwBqLwkIZTzlKEULgQGA1BoFv8BQz6Qoq9rpSKsdfJ-kNHpWcyk-A2vvcBF4VNDfPXJN7DHmSmr5uNHFBMqyr68sSAryr5iHuddEzAGKzhvTO8u4Wsi
P5hdeWp1cfHnpJqQ2xwpUm
}
@enduml