@startuml
sprite $api [84x83/16z] {
xPYBZiD624KZX50Hsdl-_szR9xKSiWxnMkwxi-yTvt2PWO7CxQyQNf9A9RkE6V0OUHspU0YahcF2uwUu36baqtl5Y9KPn5NCNENPTGigLfVH5RnEAiw5pUkI
MMnXcTyNr5GVaL0DADX03bJ31f0pad9j31UWyASipGBAjmVaHSt8X-covQUWV2_xGVV_vyDyaGDI3uSBmWHfRwEBCWVPgcLKkQxRl4oMREiyA8td2Sa_9Ang
zM8GUZwT7Rqr3QSJRJmiJemaHuF3AfvmRpuaJWYPlRTCILNXkvxNeTBJWM8RQJ_VM5wONa26BVyrBq7PpYjccTuTUqtvvoFcsE7lz7cnscZK-acg51svBo5H
5we-FxdHZf41MlZHJQ-67EB7fZo25gewMhR4u7fq0yDGDn-7N4_YSC8PDTW-dldmsNcBeeuVUztVejpwl4S1zASs4PLBf4jBPI_PJbG601KhDmH0fTckwyxo
-o-WnIXuyxVBsegqiWll8HV0ylth5jJ2xDrU1ujgSstskSw2twFLqSAS0iZ8jypOqksBn1TU5BaUwhQOdPW-Cj7YSm38LftYvkHPdORipjIoXoiJPftpUZe0
Q_QlJ3Il9-axpDoE8B-h-dekakIU5lDQcG1w0QEdIbjumARphb5OmsNB6sln-XBHcNQBTCjO__mzor2lKa25Tzafyk2nP5JVea8Pzh49GMFFrLqNmwE7YapU
PTQXypE88zNGuKLPxDdlcBa33B2NIN6qRehOStn1EZhQYNYNnjvxElIGEjVtjqxOCzGiGa1yGngQYqnrABMP0_GRqGfPNmt_KRTVh1sdHzY3G1tewoO_Gg2m
voJsgVMUXVPSbchrVb8nBsWl_GBUv7GnwpImCzSGqz2PYncdHizrzffizlpQDt95dBxKEhBdMJPpJ7bWxxKnJK3Cqa3U-liP6X0E-5kY8BOiJMIt4UhYxdY2
SkTPM--KLhCvXii2pQSQ3Q-DfAU0rLH1MNuCUgY60F1sdrFU3uE673AfOtFes_DKdXWr5JCxUvry-VrdSVqzRH3jbx_hlRUXA-_dEukwZfdeFiZhcCvZVAow
_uzV0G
}
@enduml