@startuml
sprite $web_app [64x43/16z] {
xPI5Zfin48HdoGjz__TjSAM_Mz_vAYfzWk20nr7mDvBX3m8F8jQTI1mHfemx9EQPRaAuGxhY8Di8Q4Zayj8-St313LOL5IOCUE4ZrbrohrrL6MwC7w7rYPoi
Twfq_Of1CC1-lObfmBwRJkU7bTD0ShCTWOPtfSmJRECLWt8-An001ngBzZqhi2xnBd6vr0k6IUh5rxHBnj41GdhyfP5gfOO7Sq6E3_MY6U9b4h-cDucG-6RQ
9plHS-lXkJJXyPN-AU3Uhy--sIz-lh-rtXnDqCd-jG11Qu36TlS_1rYOpFeKmAHi_FutyPhO5A3PpFdqFwoCfi7YMIWt-b2qmKoVbpSD121nD3Rb78MzWTBT
mI8pqfHmbjvKFXA9c9Ze_WmNs6RwhD0YacL2w9Swr9EgMC9Cn69HDyA4xuWFzTQYyaRb-sL6Fi0Vm9_4Vxu3
}
@enduml
