@startuml
sprite $apigee_logo [75x75/16z] {
jTY7cgCm30HWoNN69kJzd_QAl_KLvs0Wj_j_TKj4qI07srTuFdflz_J-UDgBlJMyexNT_h9j3Uzgs_PdfOx_qJURv2df4nELxjTwTaWaYJDzT9AGY1ZAUR7D
p7PeZ6RcXJYnctL8X0sLEDQD3HAJBeN61w3vg1I8Cuy6YTc6Gfnf7H9zL7ALUK9XiI5JDKTYi47zRvEnPhKX4hSGCO9hF5-JeB7usdF23fEWkvweag3HvxMy
nDE9M-PjSN1DGhXR2hvsY-6b-i091rXjnd7vXKNmDw3MabCCiLBD0AkS9pLvAa0jeuBR52cZFUuDcKnmoYbdYIIZAIwoDOIStJHG9EAoe1EXkOUOCeWJhAf8
ogNMZsnTMnKcpq3DDhckiIPYYYGg6eAzyM0JVoLdD28HTZYuz3WVoaTBKqlYh6GYCBl0AfOBbGXdcJNnvhn9HsTr_mhhuRrQPvVcHnsyluxvGQvktdcIvIZj
0wWh3EidLxgB_1ZOxYObglvVLoaUF2ablv88amAuh9K7t8Hn9YnB8kIK6kCsbvnylJzCCX4iSs3FSJiWhmbWa8dWNz5wxMpX38rE17dsP3lNjL8FLFqDcL7S
UT6EryaO81nSN-BwomH2qj-GMM8XxY7-7Mwng8eNE8MNN-0KziilS4flbvBWqDhZQZob1zkL981G6gr3bug4rEK-Gvn9K7Qv-q6aa0bfiv-wtewH-lCpTug6
NTIIk7tMhXgVdxtND-swc2uqFRUjzzlxefjzXUy
}
@enduml