@startuml
sprite $frame [79x23/16z] {
xT1LWgn040NHI2bvUlU_su6aNKRvx8DR0CNFl9YnfpxPa_zochERqHc36-vkVCHv82SneNFcMdrO4m_uD9lE34v2VDzqHZ2IxjUva8GMXccHMa2jLu8coRbo
Q2KpY6FE39I08CMMCPg8NxK14qr6wYxNrrnrVSij4cq76QfogEhgxlxRAYS3qBFSzSzMJgkhN67ByI3dDGVEVQu9kCubfN9-b_E1ZOgUv24Nu0fBeNRAkT8b
rfbGtjJ8liuuPvwiyZYEGJfO0WakoP78kjgvqclezXA3FKNmTIzl
}
@enduml