@startuml
sprite $lynkcircle [90x27/16z] {
xPC5SiGm40G_q2t__xM1gMYpgZA4yUR0mlRYza6wwIR1F5tNzV12Tg2cVL0x4lagChcF4s3MgIVBgLUJ1vZ_e8jSoF8a_vl6UWqvG_V85KOGOHHPQA6P2Eim
X0mA--IO0pZFWBjP6uRv57_9cp33FN8DZJ64d11L4AP23gXycCCZSi8WXbg_NRADOzDHDCgd0K8iTjk9XYnaE2M74tB-4U4mWysDJjmbWuqX0CyfR6akydMS
fvRMSwrhgnH39ajUrKPqsDtkTBVP8WkP5A5hhC6tHgCE7CMpBHX3laqttNGF
}
@enduml
