@startuml
sprite $lynkcircle [90x27/16z] {
xPC5hgOn30DxWDYv_srNiJJwAKkFQGHEFfY2slD2_F239Kzsdm3jizFIX7I2IXG-WVV1z42_u1B6HANW0TbIn-BJ_ZSp1iVOOoxpdE1tie_LsP_E8yhD77LF
KweoptdROgAoT2ILZqBC2eivI5Exf8jJTPaoHER9J3loIgdLJEdI94tvREPiN4zdJv_oz-PiWx6gdDpD2NhBGRsRdGd6t5LIMVKudVPcXiqS6uSmJOcDOUc3
LZEopKoQg9hAZwTEc7NPPwVC0uX3GmoOBrVcSbCSiJ5pG9pUozcmAh3RzxVRJBga633_zJpRRTjDsrHDcYaerGLahEdz-E67Nm
}
@enduml
