@startuml
sprite $okta [74x25/16z] {
xTN95S9030JH2DIJVxJiK4ygTZXQ9oprVBnxKLGTInrQRrUyB7-JQfC8bgLS1aMbBKcxq4LDgIGnQ3qtaHXLpx2hBtGa84AuajH48lM6n7vcIl6Efv80XOCa
GhmAdH7es6YI8X7aM6Mo92mvR_M1b3z9tYTcUKkY_TuPpsifJRfvJm-F3F67TsPMouqrXDYGvEK0hXL1IEpLEz8IX6IgxwntWLgId3FbVFozSuxV_I_s
}
@enduml
