@startuml
sprite $OracleEBS [92x50/16z] {
xT075lCc403XWQLi0zt_jdaYijDxp-_FtTet0lZF-VZu-13rmmQWviVaQDuvklbDcSfBKp-gT7vS3v_Zfc7WDcupJg9uH0NGqFEtOCPZXCtxluuqVbGDvT5Y
u8DZdAQ6k9vVZSUxBJ7u1JqgBzEhps-rMtHwT73b1-qPJTh1Jnd-dVluu7qcnGrGByJuOLlZCVWfFOGNjUAJ5k4sdvM9z9YO_TYwfTGRFwcuLOwpVPzGtGMG
6CKZmaDQZ1-qQoY_H29CRnuJxXV5eeCxd9MPbn5-ZvWM3RsPrHPXvvlmayhGOpP0ExUfLLJW46sqgRTEqwzDgEFvzW_xQBtzgNhZvtoKKZWAtoALRokrlF-K
rxnyDqDv1jzYPG38ocN8AlIaH2v57RyQhgnCfqRiYMJi0J0pLsKrwggoYkTAgsVmRGqEkP2hogxqXMx4i20oS6Ktm1RDYAGhmDMnnkxKNMKNsXRg9NnBfkjf
Rq_dQRUT4yp9aSsK5JxfEmQC-_tcsmJMq-R-eEvxy6rPRuneTO-HPwWlg3CNwcJhSQzRUmEPAq5q1RTkrs0tocaZfpsxyBOdK5kHI-erpauJS_g51Jd8Qx8x
uCQy24Ktd6KkPHbZ8zVJlXhVufbPWPgP1Zqp1LcP0pMyC_OWCuEsCZjzPPw0hVI2vFsdv1se9nByjCAjyikNolF-L_hu-FZu2W
}
@enduml