@startuml
sprite $pexels [76x80/16z] {
xLY7agmm3Dl4HOx__t-lvCRRmiu3czVF7Ze8HOWuS2d7T_GTonz5OrOva4ola8W1TxVTamrLskJ8C1lcXzBCU0Lh2l-COs3kvheqLCspANGMrCACyRLxM6Ov
kDsWIDqgEUWEowm6fdVFi0ZbobTQiAHMiRGRbhkVrKWshwPSiSfGXeLNGgk5Lralnw_Kov-clRnM3GmGAEGpvnBOzk4UlK2zKQCU4xEgcu-4NiQRtNXAB-Xc
KT2CluotQvLc_3LvDQP8QdqMHoJrQWe3Of99bP3JYwCwVKtu1Ejoq5_1wuc3zdc3m_xIsPw7O-uqRp1IUZrhCnMJb5w4vui-6waPVmMlyMWKzeo_23uUz9fj
L3zDhoPPVwqLcb3tLxoZMlGN1WpWi6f5BmWpKvllDWyh-GijHiy1bVRNxRwDey_F-iira6HawkFAgv4Ye9B-2bwT4LMev2-9dZvP7_KsaXsJbyHvoVf8hCoi
RHcur-fZNvzXlZugF3l-MdXLzEgNJvbYwZslbvaggrmd0NBZh-rbtbzHhQDo_uBnwlVuFf5S_nHTtv4kLlGNgFuN85oe_OhLK0C31rBTOMXBDvVL3FtfSoBj
iM4XV0J9o3OmeEx1JeAAgcn7WOJRgrzy0WpOxaavI6r6R_kpNVx9-8vt
}
@enduml