@startuml
sprite $pixabay [95x36/16z] {
xPE7YW0n24I3o808plz_xHKTTdEzznlQ6lLb8kwI_lMlIlz0kf5O7wYFnHlftywz0M7zvOcr41DP12QTeHEoCW8uMpqYvaL8ro5gC-75Q-Kr85W3wJMPKO2j
6FTItEqjfeZP_QCWoIAR5Sm1PYT2-IfI5vF5eeWuUkqQ6WTU5qr7RCYQFDtPHIvIaZXcRzbDLYmV1_c0--YEuVl2bDYyMQMsD2hXPK0jWjXjzxTlAiOAHQu7
2wWZKwGL5KPLYkxWzqDGqRnUc1Cel81r-At6nnDukTTqRctwu6F7CxUNxtEeEtWZSRWlajhEBUyd0gJ9ZF1pf37USM-vDGG9a5fIdEv1naaGHtXJPCNTVG50
L3VkUw_nr_ofaQHF54XsiB9p6QbcSdAxUqgn_RMK2mnVyZCgRUIjRafr6vzT3sOJEl2QdKVMQ4hw0QPs3-NGKJQfTlTfjbGjsJrVz-Vlpt77ntfd5ObzSzvJ
ZfBvZt1VfEYAtzTzKXiW6UmzyMQslhV-zQzB
}
@enduml