@startuml
sprite $powerautomate [60x60/16z] {
xTQ7TiCm28LXq420tlzzAtDyo8wCkjlytUEBRtRWL_GA2yMg6VP8ux5fvAuhbM5PHnBBS8AyoGoni0tLOFkC4CwOg1B4IyDk7nNYuN3v3rfaEPLZjdKz9J7B
Ujuxh7o5pOr7icAhYx15NR9-M1wjs85ayR9AgafnwvFpsct39mDrzJeViMYJBMAluTJwvCUvxVN-vBbjNTEzFxG35efJh_ZaYVKYao6v3K_sfuJuP2Gx-IGg
UyfuEJbFdij4J_LsELacpw5w7bzEvlxikTjiAnRljlcD7YUl6Upe5fdroVCkhUwFRYLkFLYtUSdoY1AiM0OhO9aiMR1Us79NhrFCOcEFuA_rwWq
}
@enduml