@startuml
sprite $powervirtualagent [72x72/16z] {
xTO5aiGm34HH5QjRykZ-frrIHKjsoiam_6782uCyNgzUXVckB7ugJc9df1TZL41t1IXjOHJWxW2rP00oP6T10fzG470v8WSO-I97bHD4XH_dE1IV3kCu9wWK
8OvtS6UESoMBMSUX6ATiSquGgwdDEnm7S8CJWsoZ8uDYcuEHOtVcj3f-7-Cq8bCxod4i7UVOTPoNmrjpUdaElC7ffOpyvwmZfkZ5oDbIct2O2w6glXohu_p4
z7GZmDmDwJBXSCLn5lFByOvJUiUfgSdyou7s7P36h4e7oLH6vTUWrd4wQJa_cKKu48mf1-NyOXh1WuXGGPznrFBVlvbWJgWu0Pgr6bi_pULeK1P3TsEvZRfC
TIk8DhXEyNnDfwuxwXfOQ-8oauce-llQsqYQ53Jbr63zdEKSbxESOw5oZeQqdECWkfmYR_B4lNhr3W
}
@enduml
