@startuml
sprite $powerpoint [69x66/16z] {
xPU7alGe38IXX2HQyhx_wruPi4U7mzXRwSB_TMdpQfflSlhNyeUSYGfHffn_ku6OXKM4k8L-iK6aZWYtRVns3xE8Yegimpj4zFXSj6s0g5JXmDCskSZVuK1X
AezgG5JY24zyFL9fDZuZyuxoVKkHAjfIz-4Z-Nw7oW5-juMaYkmkT7n-joLlr-mOxU5Jqank50PGCQF2Pz2qGnM2Ye3lum3pWoqCWr_7bCyGoYcWcF0nriDF
gkZUt86dJMQt35ntmKqJcfgiQMQivL4JeJCdJ6iAiJhi4xxaqCI0j9DX3hk_TfhQsObf2W1R6xzqmdHqWdwqgddT_C09y-J4O3Mb90upxmU2VtD2-Ro9ETpM
I_3srTHavhD40D-SSBD9QnE7zNdT16Rco2dHTfjvr6GuyUwaGBJzIiqsi-FPgnC_2zFSn90-iEzEt759YKuCW6lQoBr7dmK30L33vmhzBAd12QkomjrjossJ
S1n3p_frkvqWPW4gAdHSVlmi-TI9MdJnjKcUdLWTjvEM_RCt9tAO2e6cw2GsGR1ntwI69MhzSeUJc7N7ShnUP3WvkHUxgc8u6Jtyjedak6HpO8uvhKcTV8ph
IDBan7gc3lTDA4KdauSuhOdYw4KXq_EEpLt2B5TDE0N8h5y_TknY5qwaNRyH1dppSk37_TR8Z2tByhDy-6dZPpugE9sJ5r-MnKFQTpX3SxeW0mQVez39XuOT
HugxOyu9Kj8DrBl6tWSVW52wXJ3nkiVm4cyNPxUHdBuZ5NTmJa-WTlxHGSFKzcp_a4nQ3GSgXDCR2aDHjscHgSNxFQgKqo_9b8dUlwFzmry
}
@enduml