@startuml
sprite $prometheus [72x71/16z] {
dLS1qgeX29H1M7ZtF_0RSz8KqgyVngfqrcrRmSenY2eB2pDH-MCGYphidUOgJB-3m5huHxR0Jr2aPh0-R7c6cJv5ObrvkFZAI_a9ZAB1Z04jWlvw3hsJSRWj
MShaD_D2IGnco-1IsdCOSj8NSMTgu97FIMysstHmQFiywDE6uGjGDOkxrZRpPe3DJvoomVJ96E2kMWibtVr42KnWOsrmdsllkKILA4gyQIDjTqUdxZ3pGa6_
A7Rqo8k5qI1RI-GJ75c3FxGKu8rJkXOQVBHfJO6DuSN2Im-yNadYeqKYH_17BOMcQzcqRnTzv1Ec8kx3BtWPX2LNqUQQKcATwRk8ZIMTFcDRrmA3JjobRm-T
EFpMAUIGskDtHj-U9-NvWuIr_gRZCKiBAYE4fiz2Sf-AzIMUm25uMei6rUkv6S3-ZNr5veaz1d1DF0HEl_6nQB9vljwJFdMgufQizoQFnwH33RTKp_pC19pp
MMnM56Jwft5ma1H9_A2NVXiz9AaV_frmKdrGz6TzalMcAH_ZYtzY5ilyWEyuagqtBVzM9ii9pcAk37pczqJLooyci5Tg1H9zPZSY4lsk49i1maIxZpR_qFkw
ArzmnZsJDl_8veEdiVkP5_-07y8mjlD52svEw7xAEDGJUGHJj_eJaOtBFTZYhKEmdHMwmf1jTsn9-uNWaicT8-zVjuprAhtLt29MmrVijOHliTUit0jt2o7l
ThJM4xsRS5aFol7nuzb2KdCVyydl0jL-rYVwV_UGLhwaVkrrz3V_n5F42FyT44TSmx60xpsCOh35ktC4MkfGMXdhTd-Mgqit0I_E3upETOYM-PHDTlAFFZvV
8fSQfF7cC-VFdOKM1K2VKmZ_ta_1ZbbtlOxsAP-VFse6c8vjhqHOn9VFj3mA4iFqKSlblL1v6YIQrU569Q3SeNph89w3t8DOrFgv4-4pndy
}
@enduml