@startuml
sprite $qualtrix [88x29/16z] {
xTK5TiD040DGbJoqiUv_sd8LccwPgv3oClj31in34kyUkViuqSKl4eZ5Z82PlTmbMpWNGvdPSiC_p-NSrGSEj-6BuppCN-wYTx7QOa6ts8o8002sOEkgGLKb
5-V68pAp0k1TxbVhNaK3XtC71MwUZ8ZA70asBfzqjKgZI8k8zOQjgjIB4DJV0UmcL8O7ocy_QtAaPlTTz2uUToiAgEkW1aQrxaquTU-hne3rOAPtoQchTnTn
cDxbirt1SrSGyInNy7DSIdl6xmi0ptLVj3rCN4hRQo9dhigXUnz0ZOfSTP5QfFHmqoOkHEqDDh0-oVxXdD3p-wu7FMhuOqvZlyRzT__TAm
}
@enduml
