@startuml
sprite $sharepoint [70x67/16z] {
lPM9ZkGm24GT7nYCDV__kUiGBqaOb8bxZqAblj5BGTpXVod6-8SDe76NOYoVza3kV15yr6DId5xl0-m9mv9G2OpNcamryxZI1XoAPPh8ZfQpGPT2_MvpKkU_
0CC-nUdo1eL_KdkNIl-19YvUaBitFVcZlLJXVgy-R6YyV3CzYhkTMKSlJThLF8zYwbyc5sz_WNxIrsr0J4nE5pO4JEtkBys5Xd0OO9cbJHOY75M7fL6yTsc6
X0tDpZARt5mVMIfMaqlll5CO8qMJ2rEJmlb1J4foiA0GM2UN9GLLrGiTNHfg9leebKuMpIJf9eT0rrminUdj6mkUcmmHP-jzHgHPM6EzieZXs6ITqgpUTKyS
WsMHBlO660-TD0ldqUGYB06KHAlhhdXETaPwZxEIj55TS_5SJIxIHlgWShJXfro6ejqNtSPqjcR9HShF9awMoq_gtAFuEXSgXaNIc74LZRWzvqBPv39B62Dn
UvVB7EtbU98wJcTjoy_xeYoJ18ddN0wMIVESYxBGf86GOIV2U8ktTIJ0ay1wKnOfq3jw22z_PbIW03plYzupS3j7-Roa2WLoATNDHdVtTu6UT4eYZmHGfD2X
oK5pEMy2HA3PL6dgJbBoA2UNoNxxmQ6c96SkbiQUBz_Nxin4cbNOIGhijja4PN5-k5kbkOn2_zp59nBQ6sekubikAKmb_V9kHrroqQedoPoFVqcswToNcKtL
J0uILNIgzSxzC5vp0J3_qu_2tlWen5ikC6UKmWl9B6RL0fSQ901RU2MWIXLt8secPIY71K6jbSHtahhK9MeMnYaiQ2lWLWrBofh5_J4iQQikImfhYYMRJ7H2
AyeEJLYNpQIKu6YP9docA0H2KdCA7ojbABLWoJ7ycRPH_q6_
}
@enduml