sprite $tableau [180x37/16z] {
xPS7SXmX54ITvXEwozp_jaQ_XZ9iYzcSzzbAnAScbOeGGdaYFixNPx5IoS52nLmxXlWCpc5mjYTm7lR6LNB-EDkDd0do4hgBcN_OigpEqGdHkR0pBkByPrdv
qyAklXN_T4RO07Ybd9V_EJVdi9ap2HoUgJfV_0m6q_siplmuduOzbRC5st1EAHtg37nzS7168VOuimYPjNZsksM_su9VU6Sw0mJ97MTM04wTYLO_bld_tVdy
2yYMipCwE_4mPnBEC3yQvCIPsgdeI43dJ3AihBgLzPFLWjJePdImViOGAToyctqCMfs9Db2MijwPlJDMPmlkl5IghN_fd6EINE2GlPsSkbP841DdxTL-uCIv
a6PVoXPtSxQ3SjQ9WC4PNQqu-pYE-c7cx8HnFzkudvlmG7CGEt5cSrDd7mOhUjxsE5T9v8pTC-WlT8oRPr1pfhIRvmoG3Y1-cyuMp9sfpfHxOxyp3dVMSJJd
VjIX-TnPc3YxriIPs3w3bPsolz-UmNnPPvULzwELoLqdbo4XPGGt7YSdvtAIizo2b8T6ty7jNf1UEaxk66uXqDbs7hCOArgAHPqR00XIXWA9iSYL6paruvI7
X0YdN1AV-ZmqPxyeCWZGFv6FzZUixkUSakpdnqBlZVXqpZcdb7uWFf5pQZo1i-zdTKPv4bpukKWVvslm3m
}
@enduml