@startuml
sprite $zoominfo [75x66/16z] {
xTS7YWH128LXaOSWWjx_j9lNZKMNKqxi_YUdRpe7gdR4jf7GUx0VAV-XD3PoUi_YPxW9IjUfeFTydRBYK0aForaD03f1qLGSNHIYYq9qKH9TL4gYYvIcHBP6
fGGgKsE9V431tDruLihjaj99sGyfMv2S7r1YRvUCsgJR6IP4kwIFA4c_9BSZwIrBM9MiN-97bBnTShgKn108EYJIZMd0aTBSl45LgbCf6HMeYbIdK96IQjYC
9rMGobHAKjkWOImvvFKYmlIHYE3jXf-FFg1i-WImVXANbArJaTGT3XN_eTZqrmK_FXbTXAxSqJC
}
@enduml